import React, { useEffect, useState } from 'react';
import { reportDownloads as staticReportDownloads, ReportAsset } from '../data';
import { fetchReports, API_BASE } from '../api';

export function ReportsPage() {
  const [reportDownloads, setReportDownloads] = useState<ReportAsset[]>(staticReportDownloads);
  const [errorMsg, setErrorMsg] = useState<string | null>(null);

  async function handleDownload(report: ReportAsset, e: React.MouseEvent) {
    if (!report.reportId) return; // If it's a regular link (like the Folder), let it behave normally
    e.preventDefault();
    setErrorMsg(null);
    try {
      const res = await fetch(`${API_BASE}/v1/reports/${report.reportId}/pdf`);
      if (!res.ok) {
        const errorData = await res.json().catch(() => ({}));
        throw new Error(errorData.error || `Failed to download report: ${res.statusText}`);
      }
      const blob = await res.blob();
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `cloudspecter-${report.reportId}.pdf`;
      document.body.appendChild(a);
      a.click();
      a.remove();
      window.URL.revokeObjectURL(url);
    } catch (err: any) {
      setErrorMsg(err.message || String(err));
    }
  }

  useEffect(() => {
    fetchReports().then((data) => setReportDownloads(data)).catch(() => undefined);
  }, []);

  return (
    <div className="space-y-6">
      <section className="rounded-[2rem] border border-white/10 bg-white/5 p-6 shadow-glow backdrop-blur-xl">
        <p className="text-xs font-semibold uppercase tracking-[0.35em] text-signal-100/90">Reports</p>
        <h3 className="mt-3 text-3xl font-bold tracking-tight text-white">Download PDFs for the room</h3>
        <p className="mt-4 max-w-3xl text-sm leading-7 text-slate-300">
          The report page is built for handoff. It points to PDF artifacts generated by the scanner pipeline so stakeholders can pull the latest summary without leaving the dashboard.
        </p>
      </section>

      <section className="grid gap-4 xl:grid-cols-2">
        {reportDownloads.map((report) => (
          <article key={report.title} className="rounded-[2rem] border border-white/10 bg-white/5 p-5 shadow-glow backdrop-blur-xl">
            <div className="flex items-start justify-between gap-4">
              <div>
                <h4 className="text-lg font-semibold text-white">{report.title}</h4>
                <p className="mt-2 text-sm leading-6 text-slate-400">{report.description}</p>
              </div>
              <span className="rounded-full bg-signal-500/15 px-3 py-1 text-xs font-semibold uppercase tracking-[0.24em] text-signal-100">
                {report.badge}
              </span>
            </div>
            <div className="mt-5 flex flex-wrap gap-3">
              <a
                href={report.href || '#'}
                onClick={(e) => handleDownload(report, e)}
                download={!report.reportId}
                className="inline-flex items-center rounded-full bg-signal-400 px-4 py-2 text-sm font-semibold text-midnight-950 transition hover:bg-signal-100"
              >
                {report.reportId ? 'Generate PDF' : 'Open'}
              </a>
              <span className="inline-flex items-center rounded-full border border-white/10 bg-black/20 px-4 py-2 text-sm text-slate-300">
                {report.reportId ? `Dynamic: ${report.reportId}` : report.href}
              </span>
            </div>
          </article>
        ))}
      </section>

      {errorMsg && (
        <section className="rounded-[2rem] border border-ember-500/30 bg-ember-500/10 p-5 text-sm leading-7 text-ember-300">
          <span className="font-semibold">Download Error:</span> {errorMsg}
        </section>
      )}
    </div>
  );
}
